#include "hal_data.h"
//#include "examples/hello_world/main_functions.h"

SSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
SSP_CPP_FOOTER

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */

}

